### ISSUE TITLE
Profile - No Profile

### ISSUE THREAD

**Issue by mrdeepmind** [vagnum08/cpupower-gui#78]
After applying any of the saved profiles, it says No profile.

It does not affect the function of the app, it works and applies the selected profile but just displays as "No profile" even the profile is already applied.

![cpupow-git](https://user-images.githubusercontent.com/56367254/154738849-e51e5c10-e8d3-43be-8691-179e98e2e90a.png)

Distro: Arch Linux 
![neofetch](https://user-images.githubusercontent.com/56367254/154739100-57200b55-ae7b-470d-9677-3ca8170ec126.png)

cpupower-gui-git (AUR) version "cpupower-gui 1.0.0" 

https://aur.archlinux.org/packages/cpupower-gui-git

**Comment by vagnum08** [comment]
Hey,

This is not buggy behaviour.

When you select a profile from the drop-down list and click on `Apply`, it applies the selected profile and resets the drop-down.


I could have made it the other way and kept the selected profile after applying the settings.

However, any change outside the app will invalidate the selection, 
since the profile is just a bunch of frequency settings. This will also happen if you close and reopen the app, there no way to tell if a profile is applied as it not inherent to the CPU.

I have to make it clear (README, tooltip, FAQ) that this happens, so new users know about it.

**Comment by vagnum08** [comment]
Changing this to enhancement.
