### ISSUE TITLE
Doesn't minimize to notification area

### ISSUE THREAD

**Issue by marceloengecom** [vagnum08/cpupower-gui#84]
Hello,

The CPUPower-GUI doesn't minimize to notification area. The software don't contain thir resource?

My System:
Operating System: Ubuntu 21.10
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-39-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-2630QM CPU @ 2.00GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 3000

Thanks,
Marcelo Costa

**Comment by vagnum08** [comment]
Hi, to minimize to the notification area you need to have libappindicator installed.

**Comment by realmain** [comment]
Was about to open an issue, but seeing that this issue is still open:

I am personally having this issue. I am running Arch and I have `libappindicator-gtk3` installed already.

When you launch the app, it opens the window and also has the icon in the tray that is also usable. The issue is when you close the window, it doesn't minimize to tray, it closes out of the whole app. It doesn't look like there is a minimize button the app window itself.

I also checked the settings, and there doesn't seem to be an option to "Close to tray" or the like. Some programs I use have an option in settings to minimize to tray when closed.

**Comment by wraith3690** [comment]
I have this issue as well OS Linux mint 21.1 mate version at first there was no tray icon so I installed the suggested package above (gir1.2-appindicator3-0.1) now there is a tray icon but there is no way to minimise to the tray you can only click the x which closes the program

**Comment by vagnum08** [comment]
@realmain I will see what I can do with the close to tray.
